### ISSUE TITLE
Still error

### ISSUE THREAD

**Issue by hendisantika** [darrachequesne/spring-data-mongodb-datatables#8]
I think I already followed the docs.
But Why I still got error:

https://github.com/hendisantika/SpringBoot-DataTable

![image](https://user-images.githubusercontent.com/3713580/92824982-41871700-f3f9-11ea-92a2-4e652dc11e03.png)

![image](https://user-images.githubusercontent.com/3713580/92825000-46e46180-f3f9-11ea-874c-f75486647416.png)

Any suggestion?

**Comment by darrachequesne** [comment]
Closed as duplicate of https://github.com/darrachequesne/spring-data-jpa-datatables-sample/issues/13.
